server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        -id: payment
        uri: http://localhost:8080/
        predicates:
          -Path=api/v1/payment/*
eureka:
  register-with-eureka: true
  fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka