apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
data:
  SPRING_PROFILES_ACTIVE: kube
  MONGODB_URI: mongodb+srv://root:root@cluster0.rz1qx1b.mongodb.net/?retryWrites=true&w=majority



