version: '3.9'
services:
  app:
    image:   users-microservice
    container_name: users-microservice
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testDB
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgresdb

  postgresdb:
    image: postgres:13.1-alpine
    container_name: postgresdb-users
    ports:
      - "5432:5431"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testDB
      - POSTGRES_PORT=5432
    volumes:
      - postgresdb:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  pgadmin:
    container_name: pgadmin-users
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "82:80"
    restart: unless-stopped
    logging:
      driver: "none"

volumes:
    postgresdb:
    pgadmin:

