spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:users}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672


      #redis:
      # host: 127.0.0.1
      #port: 6379
      # cache:
      #redis:
      #time-to-live: 3600
    #cache-null-values: false
  mail:
    protocol: smtp
    host: smtp.mailtrap.io
    port: 2525

    username: a21f2f1308ac72
    password: c4a7231f34f319

app:
  jwtSecret: SecretKey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 1200000
  paypal:
    mode: sandbox
    clientID: 
    secret: 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchanges:
    internal: users.exchange
  queues:
    payment: payment.queue
  routing-keys:
    internal-payment: internal.payment.routing-key

