spring:
  application:
    name: users-microservice
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:testDB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true



      #redis:
      # host: 127.0.0.1
      #port: 6379
      # cache:
      #redis:
      #time-to-live: 3600
    #cache-null-values: false
  mail:
    protocol: smtp
    host: smtp.mailtrap.io
    port: 2525
    username: 
    password: 
server:
  port: 8081

app:
  jwtSecret: SecretKey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 1200000
  paypal:
    mode: sandbox
    clientID: 
    secret: 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
