spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: test
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  mail:
      protocol: smtp
      host: smtp.mailtrap.io
      port: 2525
      username: a21f2f1308ac72
      password: c4a7231f34f319
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


rabbitmq:
  exchanges:
    internal: notification.exchange
  queues:
    notification: notification.queue
    email: email.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
    internal-email: internal.email.routing-key