eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
      - id: users
        uri: lb://users
        predicates:
          - Path=/api/v1/auth/*
          - Method=GET,POST,PUT,DELETE
      - id: payment
        uri: http://localhost:8080/payment
        predicates:
          - Path=/api/v1/payment/*
          - Method=GET,POST,PUT,DELETE


