eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
      - id: users
        uri: lb://users
        predicates:
          - Path=/auth/*
          - Method=GET,POST,PUT,DELETE,OPTIONS
      - id: payment
        uri: lb://payment
        predicates:
          - Path=/payment/*
          - Method=GET,POST,PUT,DELETE,OPTIONS
        filters:
          - AuthFilter

      - id: transaction
        uri: lb://transaction
        predicates:
          - Path=/transaction/*
          - Method=GET,POST,PUT,DELETE,OPTIONS
        filters:
          - AuthFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - x-requested-with
              - Authorization
              - Content-Type
              - Content-Length
              - Authorization
              - credential
              - X-XSRF-TOKEN
              - Accept
              - Referer
              - refreshToken
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS

client:
  instancesUri:
    users: http://localhost:8081/auth/

app:
  jwtSecret: SecretKey

