spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost9411

eureka:
    client:
      fetch-registry: false
      register-with-eureka: false
    instance:
      preferIpAddress: true
      hostname: localhost
      ipAddr: 127.0.0.1
server:
      port: 8761